collections:
- name: community.docker
- name: community.sops
- name: ansible.posix
- name: devsec.hardening
- name: prometheus.prometheus

roles:
- name: artis3n.tailscale
  version: "v4.6.0"
- name: cchurch.admin-users
  version: "0.8.6"
- name: geerlingguy.docker
  version: "7.4.7"
- name: geerlingguy.mysql
  version: "4.3.4"
- name: geerlingguy.pip
  version: "3.1.0"
- name: ypsman.ipv6_disable
- name: linux-system-roles.timesync
