server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/positions.yaml

clients:
  - url: 'http://loki:3100/loki/api/v1/push'
    external_labels:
      host:  "${HOSTNAME}"
      constellation: local

scrape_configs:

- job_name: journal
  journal:
    json: false
    labels: {job: systemd-journal}
    max_age: 12h
    path: /var/log/journal
  relabel_configs:
  - source_labels: [__journal__systemd_unit]
    target_label: unit

- job_name: system
  static_configs:
  - labels:
      __path__: /var/log/syslog
      job: syslog

- job_name: container
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
  pipeline_stages:
    - static_labels:
        job: container
  relabel_configs:
    - source_labels: [__meta_docker_container_label_com_docker_stack_namespace]
      target_label: 'stack'
    - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
      target_label: 'service_name'
